# Configuration for the documentation hosted via Github pages 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Modelica DisHeatLib library
description: DisHeatLib is a Modelica library for dynamic modelling of district heating networks.
show_downloads: true
